// src/components/header/header.component.ts

import { Component, ChangeDetectionStrategy } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
})
export class HeaderComponent {
  navLinks = [
    { path: '/', label: 'Portal' },
    { path: '/forum', label: 'Forum' },
    { path: '/rules', label: 'Règlement' },
    { path: '/universe', label: 'Univers' },
  ];
}


<header class="bg-black border-b-2 border-yellow-600 shadow-lg shadow-yellow-600/10">
  <div class="container mx-auto px-4">
    <div class="flex items-center justify-between h-20">
      <div class="flex items-center space-x-4">
        <a routerLink="/" class="flex items-center space-x-3 text-yellow-400 hover:text-yellow-300 transition-colors">
          <svg class="w-10 h-10" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 2L9.44 8.65L2 9.71L7.55 14.88L6.18 22L12 18.5L17.82 22L16.45 14.88L22 9.71L14.56 8.65L12 2Z" />
          </svg>
          <span class="text-3xl font-bold font-cinzel tracking-wider">SWOR.FR</span>
        </a>
      </div>
      <nav class="hidden md:flex items-center space-x-6">
        @for (link of navLinks; track link.path) {
          <a [routerLink]="link.path" routerLinkActive="text-yellow-400 border-b-2 border-yellow-400" [routerLinkActiveOptions]="{exact: true}" class="text-lg text-gray-300 hover:text-yellow-400 transition-colors duration-300 pb-1 border-b-2 border-transparent">{{ link.label }}</a>
        }
      </nav>
      <div class="flex items-center">
        <a routerLink="/profile" class="flex items-center space-x-2 text-gray-300 hover:text-yellow-400 transition-colors">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd" />
          </svg>
          <span class="hidden lg:inline">Mon Profil</span>
        </a>
      </div>
    </div>
  </div>
</header>

// src/shared/components/Header.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { User } from 'lucide-react';
import { cn } from '@/shared/utils/cn';

const navLinks = [
  { path: '/', label: 'Portal' },
  { path: '/forum', label: 'Forum' },
  { path: '/rules', label: 'Règlement' },
  { path: '/universe', label: 'Univers' },
];

export default function Header() {
  const pathname = usePathname();

  return (
    <header className="sticky top-0 z-50 w-full border-b border-white/5 bg-black/50 backdrop-blur-xl">
      <div className="container mx-auto px-6">
        <div className="flex items-center justify-between h-20">
          <div className="flex items-center gap-8">
            <Link href="/" className="flex items-center group py-2">
              <div className="flex flex-col items-center justify-center leading-[0] font-starwars text-yellow-500 transition-transform group-hover:scale-105">
                <span className="text-2xl tracking-tighter">SW</span>
                <span className="text-2xl tracking-tighter -mt-3">oR</span>
              </div>
            </Link>

            <nav className="hidden md:flex items-center gap-1">
              {navLinks.map((link) => {
                const isActive = pathname === link.path || (link.path !== '/' && pathname.startsWith(link.path));
                return (
                  <Link
                    key={link.path}
                    href={link.path}
                    className={cn(
                      "px-4 py-2 text-sm font-medium rounded-full transition-all duration-200",
                      isActive 
                        ? "text-white bg-white/5" 
                        : "text-zinc-400 hover:text-white hover:bg-white/5"
                    )}
                  >
                    {link.label}
                  </Link>
                );
              })}
            </nav>
          </div>

          <div className="flex items-center gap-4">
            <Link 
              href="/profile" 
              className="flex items-center justify-center w-10 h-10 rounded-full bg-zinc-900 border border-white/5 text-zinc-400 hover:text-white hover:border-white/20 transition-all"
            >
              <User className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </div>
    </header>
  );
}
