// src/app/universe/page.tsx
export default function UniversePage() {
  return (
    <div className="bg-gray-950/70 p-8 rounded-lg border border-yellow-800/30 prose prose-invert max-w-none prose-h1:text-yellow-400 prose-h1:font-cinzel prose-h2:text-yellow-500 prose-a:text-yellow-400 hover:prose-a:text-yellow-300">
      <h1>Contexte de l'Univers</h1>
      <p>Notre forum explore trois périodes distinctes de la saga Star Wars, offrant des expériences de jeu variées. Chaque période est une instance séparée, permettant aux personnages de vivre des aventures uniques à leur époque.</p>

      <h2>1. La Guerre des Clones (22-19 BBY)</h2>
      <p>La galaxie est en proie à une guerre totale. La République Galactique, défendue par les Chevaliers Jedi et son armée de clones, affronte la Confédération des Systèmes Indépendants et son armée de droïdes. Incarnez un Jedi menant ses troupes, un soldat clone sur le front, un politicien naviguant les intrigues de Coruscant, ou un citoyen tentant de survivre au chaos.</p>
      <ul>
        <li><strong>Factions Majeures :</strong> République Galactique, Ordre Jedi, Alliance Séparatiste.</li>
        <li><strong>Ambiance :</strong> Conflit militaire à grande échelle, intrigues politiques, héroïsme et tragédie.</li>
      </ul>
      
      <h2>2. La Guerre Civile Galactique (0-4 ABY)</h2>
      <p>L'Empire Galactique règne d'une main de fer. L'Empereur Palpatine et son bras droit, Dark Vador, traquent les derniers Jedi et écrasent toute dissidence. Mais un espoir subsiste : l'Alliance Rebelle, une coalition de mondes et de combattants de la liberté, lutte pour restaurer la République. Choisissez votre camp : rejoignez la Rébellion, imposez l'ordre Impérial, ou tracez votre propre voie en tant que contrebandier ou chasseur de primes dans les bas-fonds de la galaxie.</p>
      <ul>
        <li><strong>Factions Majeures :</strong> Empire Galactique, Alliance Rebelle, Syndicats du Crime.</li>
        <li><strong>Ambiance :</strong> Guerre asymétrique, espionnage, lutte de l'opprimé contre le tyran.</li>
      </ul>

      <h2>3. L'Après-Empire (Légendes, à partir de 5 ABY)</h2>
      <p>L'Empereur est mort et l'Étoile de la Mort a été détruite, mais la guerre est loin d'être terminée. L'Alliance Rebelle se transforme en Nouvelle République, cherchant à unifier la galaxie. Cependant, les vestiges de l'Empire, dirigés par des Moffs et des seigneurs de guerre ambitieux, se battent pour conserver le pouvoir. Cette période, inspirée de l'univers "Légendes", est un terrain de jeu où de nouvelles puissances peuvent émerger et où le futur de la galaxie est incertain.</p>
      <ul>
        <li><strong>Factions Majeures :</strong> Nouvelle République, Vestiges de l'Empire, factions indépendantes.</li>
        <li><strong>Ambiance :</strong> Reconstruction, exploration, lutte de pouvoir dans une galaxie fracturée.</li>
      </ul>
    </div>
  );
}

// src/components/universe/universe.component.ts

import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-universe',
  templateUrl: './universe.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
})
export class UniverseComponent {}


<div class="bg-gray-950/70 p-8 rounded-lg border border-yellow-800/30 prose prose-invert max-w-none prose-h1:text-yellow-400 prose-h1:font-cinzel prose-h2:text-yellow-500 prose-a:text-yellow-400 hover:prose-a:text-yellow-300">
  <h1>Contexte de l'Univers</h1>
  <p>Notre forum explore trois périodes distinctes de la saga Star Wars, offrant des expériences de jeu variées. Chaque période est une instance séparée, permettant aux personnages de vivre des aventures uniques à leur époque.</p>

  <h2>1. La Guerre des Clones (22-19 BBY)</h2>
  <p>La galaxie est en proie à une guerre totale. La République Galactique, défendue par les Chevaliers Jedi et son armée de clones, affronte la Confédération des Systèmes Indépendants et son armée de droïdes. Incarnez un Jedi menant ses troupes, un soldat clone sur le front, un politicien naviguant les intrigues de Coruscant, ou un citoyen tentant de survivre au chaos.</p>
  <ul>
    <li><strong>Factions Majeures :</strong> République Galactique, Ordre Jedi, Alliance Séparatiste.</li>
    <li><strong>Ambiance :</strong> Conflit militaire à grande échelle, intrigues politiques, héroïsme et tragédie.</li>
  </ul>
  
  <h2>2. La Guerre Civile Galactique (0-4 ABY)</h2>
  <p>L'Empire Galactique règne d'une main de fer. L'Empereur Palpatine et son bras droit, Dark Vador, traquent les derniers Jedi et écrasent toute dissidence. Mais un espoir subsiste : l'Alliance Rebelle, une coalition de mondes et de combattants de la liberté, lutte pour restaurer la République. Choisissez votre camp : rejoignez la Rébellion, imposez l'ordre Impérial, ou tracez votre propre voie en tant que contrebandier ou chasseur de primes dans les bas-fonds de la galaxie.</p>
  <ul>
    <li><strong>Factions Majeures :</strong> Empire Galactique, Alliance Rebelle, Syndicats du Crime.</li>
    <li><strong>Ambiance :</strong> Guerre asymétrique, espionnage, lutte de l'opprimé contre le tyran.</li>
  </ul>

  <h2>3. L'Après-Empire (Légendes, à partir de 5 ABY)</h2>
  <p>L'Empereur est mort et l'Étoile de la Mort a été détruite, mais la guerre est loin d'être terminée. L'Alliance Rebelle se transforme en Nouvelle République, cherchant à unifier la galaxie. Cependant, les vestiges de l'Empire, dirigés par des Moffs et des seigneurs de guerre ambitieux, se battent pour conserver le pouvoir. Cette période, inspirée de l'univers "Légendes", est un terrain de jeu où de nouvelles puissances peuvent émerger et où le futur de la galaxie est incertain.</p>
  <ul>
    <li><strong>Factions Majeures :</strong> Nouvelle République, Vestiges de l'Empire, factions indépendantes.</li>
    <li><strong>Ambiance :</strong> Reconstruction, exploration, lutte de pouvoir dans une galaxie fracturée.</li>
  </ul>
</div>
